### ISSUE TITLE
Minor Roadmap improvements

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#423]
- [x] Admin Roadmap management grid grouping should follow phase sort order
- [x] Don't show Github icon in dataview if there are no GH links
- [x] Go directly to GH link on GH icon click if there is only one link (instead of showing menu with that link)
- [x] Dataview groups alpha-sort by phase.sortOrder (instead of numeric sort - try a sortOrder on a phase of 1000 and you will see its group floats to the top of the list)
